######################## default configuration ####################
baseURL = "/"  # Remove this
languageCode = 'en-us'
title = 'Women In Tech Blog'
pygmentsstyle = 'monokai'
theme = "bookworm-light"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
# googleAnalytics = "" # example : UA-123-45
# disqus short name
# disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Image Processing ##############################
[imaging]
quality = "95"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Mulish:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Mulish"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#750550"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#9B2B77"

#################### default parameters ################################
[params]
logo = "images/logo.svg"
logo_width = "60px"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "WomenInTech Blog"
# contact form action
contact_form_action = "https://formspree.io/f/xayvvrjy" 
# contact form works with https://formspree.io
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "Copyright Â©2023 Women in Tech Blog - Powered by [Gethugothemes](https://gethugothemes.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = "bookworm"
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us8.list-manage.com/subscribe/post?u=47189034d24dd3cfecd90b30a&amp;id=a4fa5a3c61" # replace this url with yours
mailchimp_form_name = "b_47189034d24dd3cfecd90b30a_a4fa5a3c61" # replace this code with yours
title = "Subscribe to our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
name = "Home"
url = "/"
weight = 1
  
[[menu.main]]
name = "About"
url = "about/"
weight = 3
  
[[menu.main]]
name = "Contact"
url = "contact/"
weight = 4
  
[[menu.main]]
weight = 6
url = "#"
name = "Pages"
hasChildren = true

  [[menu.main]]
  parent = "Pages"
  name = "Author"
  url = "author/"
  weight = 1
  
  [[menu.main]]
  parent = "Pages"
  name = "Tags"
  url = "tags/"
  weight = 2
  
  [[menu.main]]
  parent = "Pages"
  name = "Category"
  url = "categories/"
  weight = 3
  

############################# Footer Menu ########################
[[menu.footer]]
name = "About"
url = "about/"
weight = 1

[[menu.footer]]
name = "Authors"
url = "author/"
weight = 2


# Social Icons
[[params.social]]
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
url = "https://www.linkedin.com/company/women-in-tech-shoutouts"

[[params.social]]
icon = "lab la-twitter" # https://icons8.com/line-awesome
url = "https://twitter.com/W_TechShoutOuts/"

[[params.social]]
icon = "lab la-instagram" # https://icons8.com/line-awesome
url = "https://www.instagram.com/w_techshoutouts/"

[[params.social]]
icon = "lab la-youtube" # https://icons8.com/line-awesome
url = "https://www.youtube.com/channel/UCAhsktTF6b8WagxFObpg6Xw"